name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache
        key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}  # Adjust this key as needed

    - name: Copy files to the server
      run: |
        ssh -o StrictHostKeyChecking=no root@35.202.133.83 "rm -rf /var/www/html/*"
        scp -r * root@3.87.222.112:/var/www/html/

    - name: Restart Apache
      run: |
        ssh -o StrictHostKeyChecking=no root@35.202.133.83 "sudo systemctl restart apache2"
