name: Deploy Node.js API to AWS

on:
  push:
    branches:
      - main  # Adjust to the branch you use for deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.DEPLOYSECRET }}

    - name: Deploy to EC2
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@3.87.222.112 << 'EOF'
          # Navigate to the project directory (or clone if missing)
          if [ ! -d "/home/ec2-user/sms" ]; then
            git clone https://github.com/james-otieno/SmsApi.git /home/ec2-user/my-node-api
          fi

          cd /home/ec2-user/sms

          # Pull the latest changes
          git pull origin main

          # Install dependencies
          npm install

          # Restart the application with PM2
          pm2 restart app || pm2 index.js --name sms

          # Save the PM2 process list for startup on reboot
          pm2 save
        EOF
